version: "3.3"
services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-server
    ports:
      - "5000:5000"
    volumes:
      - "./server:/usr/app"
      - "/usr/app/node_modules"

  client:
      build:
        context: ./client
        dockerfile: Dockerfile
      container_name: react-client
      ports:
        - "80:3000"
      volumes:
        - "./client:/usr/app"
        - "/usr/app/node_modules"
      environment:
        - CHOKIDAR_USE_POLLING=true

  mongo-db:
    image: mongo
#    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
#    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://username:password@mongo-db:27017/

